name: CI/CD - Docker, Trivy, ECR & EC2

on:
  push:
    branches: ["main"]

jobs:
  build-push-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      # ---------------- AWS AUTH ----------------
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-south-1

      - name: Login to Amazon ECR
        uses: aws-actions/amazon-ecr-login@v2

      # ---------------- BUILD ----------------
      - name: Build Docker image
        run: |
          docker build -t ${{ secrets.AWS_ECR_REPOSITORY }}:latest .

      # ---------------- SECURITY SCAN (OPTIONAL) ----------------
      # Uncomment when ready
      # - name: Trivy Image Scan
      #   uses: aquasecurity/trivy-action@0.20.0
      #   with:
      #     image-ref: ${{ secrets.AWS_ECR_REPOSITORY }}:latest
      #     severity: HIGH,CRITICAL
      #     exit-code: 1
      #     scanners: vuln
      #   env:
      #     TRIVY_CLEAR_CACHE: "true"

      # ---------------- PUSH ----------------
      - name: Push Docker image to ECR
        run: |
          docker push ${{ secrets.AWS_ECR_REPOSITORY }}:latest

      # ---------------- DEPLOY ----------------
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.6
        with:
          debug: true
          host: ${{ secrets.AWS_EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.AWS_EC2_SSH_KEY }}
          port: 22
          script: |
            docker pull ${{ secrets.AWS_ECR_REPOSITORY }}:latest

            docker stop note-web || true
            docker rm note-web || true

            docker run -d \
              --name note-web \
              --restart=always \
              -p 4000:3000 \
              ${{ secrets.AWS_ECR_REPOSITORY }}:latest
